#!/usr/bin/env python3
"""Generate the routed swipe-corpus digest and the human review file.

    python3 scripts/build-swipe-digest.py

Reads `corpus/swipe/entries.json` and writes:

- `references/22-swipe-corpus.md`, the digest loaded with the craft stack;
- `corpus/swipe/REVIEW.md`, the checklist of drafted annotations awaiting correction.

The digest carries annotated openings grouped by awareness, not raw ad data. Raw
data stays in entries.json so the agent's context is spent on the teaching layer.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTRIES = ROOT / "corpus" / "swipe" / "entries.json"
DIGEST = ROOT / "references" / "22-swipe-corpus.md"
REVIEW = ROOT / "corpus" / "swipe" / "REVIEW.md"

BANDS = [
    ("UWA", "Unaware openings", "The product arrives late or not at all. These earn attention before they sell."),
    ("PRA", "Problem aware openings", "The problem is named early, the product is held back."),
    ("SLA", "Solution aware openings", "The mechanism or the comparison does the work."),
    ("PDA", "Product aware openings", "The product leads. Proof, offer and objection carry the argument."),
    (None, "Awareness not computed", "Static, carousel or DCO entries, or video where Foreplay reported no product-mention time."),
]


def hook_line(entry: dict) -> str:
    content = entry["content"]
    if content.get("headline"):
        return content["headline"].strip()
    transcription = (content.get("transcription") or "").split()
    if transcription:
        return " ".join(transcription[:16]) + "..."
    return "(no headline or transcript)"


def evidence_line(entry: dict) -> str:
    evidence = entry["evidence"]
    parts = []
    days = evidence.get("running_days")
    if days is not None:
        parts.append(f"{days} days running")
    if evidence.get("live"):
        parts.append("still live")
    ratio = entry["awareness"].get("mention_ratio")
    if ratio == -1:
        parts.append("product reported as never named")
    elif ratio is not None:
        parts.append(f"product named {ratio:.0%} through")
    return ", ".join(parts) or "no longevity data"


def render_entry(entry: dict) -> list[str]:
    annotation = entry["annotation"]
    brand = entry["brand"].get("name") or "brand not resolved"
    lines = [f'### "{hook_line(entry)}"', ""]
    opening = annotation.get("opening_type") or "not assessed"
    lines.append(
        f"{brand}, {entry['format']}. {opening.capitalize()}. {evidence_line(entry)}."
    )
    lines.append("")
    carriers = annotation.get("must_have_carriers") or {}
    named = [
        f"- {label}: {carriers[key]}"
        for key, label in (
            ("emotion", "Emotion"),
            ("curiosity_gap", "Curiosity gap"),
            ("high_stakes", "High stakes"),
        )
        if carriers.get(key)
    ]
    if named:
        lines.extend(named)
        lines.append("")
    if annotation.get("why_it_works"):
        lines.append(annotation["why_it_works"])
        lines.append("")
    if annotation.get("teaching_note"):
        lines.append(f"**The move:** {annotation['teaching_note']}")
        lines.append("")
    if entry.get("foreplay_url"):
        lines.append(f"[See the ad in Foreplay]({entry['foreplay_url']})")
        lines.append("")
    return lines


def build_digest(entries: list[dict]) -> str:
    annotated = [e for e in entries if e.get("annotation")]
    reviewed = [e for e in annotated if e.get("reviewed")]
    boards = sorted({e["board"] for e in entries if e.get("board")})

    out = [
        "# Swipe corpus: annotated openings that ran",
        "",
        "Real direct-response ads with the move named, so a pattern can be applied to a product that",
        "is not in this file. `16-hook-formats.md` gives the taxonomy and",
        "`20-hook-quality-standard.md` gives the gate. This file is the worked evidence.",
        "",
        "Generated by `scripts/build-swipe-digest.py` from `corpus/swipe/entries.json`. Do not edit by",
        "hand.",
        "",
        "## What the evidence is and is not",
        "",
        f"- {len(entries)} entries, {len(annotated)} annotated, {len(reviewed)} human-reviewed.",
        f"- Source: curated Foreplay board{'s' if len(boards) != 1 else ''} "
        f"{', '.join(boards) if boards else 'none'}, plus any discovery backfill.",
        "- **Longevity is behavioural evidence, never performance.** A long-running ad tells you an",
        "  operator kept funding it. It is not a measured return, and a neglected ad can run for a year.",
        "- **Awareness codes are a proxy.** Where a code is present it was computed from how long the ad",
        "  runs before naming the product. An ad can name the product immediately and still address an",
        "  unaware buyer. Treat the code as a sort, not a fact.",
        "- **The never-named sentinel is unreliable.** At least one entry reports the product as never",
        "  named while its transcript names it. Check before relying on that value.",
        "- Annotations marked unreviewed are one reading, not an established fact. Weight them",
        "  accordingly and never cite one as proof.",
        "",
        "## How to use this",
        "",
        "1. Find the band matching the awareness state you are writing for.",
        "2. Read the moves, not the words. Copying a line from here produces a worse ad than the",
        "   original and may copy a claim this brand cannot support.",
        "3. Check the pattern against the brand's own tested results first. A result in the brand's test",
        "   register outranks anything here.",
        "4. Every claim in a corpus ad belongs to that brand. Reusing the claim is not permitted; reusing",
        "   the structure is the point.",
        "",
    ]

    for code, title, blurb in BANDS:
        group = [e for e in annotated if e["awareness"].get("code") == code]
        if not group:
            continue
        group.sort(key=lambda e: -((e.get("evidence") or {}).get("running_days") or 0))
        out.extend([f"## {title}", "", blurb, ""])
        for entry in group:
            out.extend(render_entry(entry))

    return "\n".join(out).rstrip() + "\n"


def build_review(entries: list[dict]) -> str:
    annotated = [e for e in entries if e.get("annotation") and not e.get("reviewed")]
    missing = [e for e in entries if e.get("annotatable") and not e.get("annotation")]
    blocked = [e for e in entries if not e.get("annotatable")]

    out = [
        "# Swipe corpus review",
        "",
        "Every annotation below was drafted by the agent and is marked `reviewed: false`. Correcting a",
        "wrong reading is much cheaper than writing one from blank, and your corrections are the actual",
        "asset here.",
        "",
        "To approve an entry, fix anything wrong in `entries.json` and set `\"reviewed\": true`. Then run",
        "`python3 scripts/build-swipe-digest.py`.",
        "",
        f"## Awaiting review ({len(annotated)})",
        "",
    ]
    for entry in annotated:
        brand = entry["brand"].get("name") or entry["brand"]["id"]
        annotation = entry["annotation"]
        out.append(f"- [ ] **{hook_line(entry)}**  ")
        out.append(
            f"      {brand}, {entry['format']}, {evidence_line(entry)}. "
            f"Read as {annotation.get('opening_type') or 'not assessed'}.  "
        )
        out.append(f"      `{entry['id']}`")
    out.append("")

    if missing:
        out.extend([f"## Annotatable but not yet drafted ({len(missing)})", ""])
        for entry in missing:
            brand = entry["brand"].get("name") or entry["brand"]["id"]
            out.append(f"- [ ] {hook_line(entry)}  ({brand}, {entry['format']}, `{entry['id']}`)")
        out.append("")

    if blocked:
        out.extend(
            [
                f"## Not annotatable ({len(blocked)})",
                "",
                "Foreplay returned no headline, primary text or transcript for these, so there is nothing",
                "to read. Mostly DCO containers. They stay in the corpus so the count is honest, and they",
                "will pick up content if Foreplay processes them later.",
                "",
            ]
        )
        for entry in blocked:
            brand = entry["brand"].get("name") or entry["brand"]["id"]
            out.append(f"- {brand}, {entry['format']}, `{entry['id']}`")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    if not ENTRIES.is_file():
        print(f"{ENTRIES} not found. Run scripts/sync-swipe-corpus.py first.", file=sys.stderr)
        return 2
    entries = json.loads(ENTRIES.read_text())["entries"]
    DIGEST.write_text(build_digest(entries))
    REVIEW.write_text(build_review(entries))
    annotated = sum(1 for e in entries if e.get("annotation"))
    reviewed = sum(1 for e in entries if e.get("reviewed"))
    print(f"Wrote {DIGEST.relative_to(ROOT)} ({len(DIGEST.read_text()):,} chars)")
    print(f"Wrote {REVIEW.relative_to(ROOT)}")
    print(f"{len(entries)} entries, {annotated} annotated, {reviewed} reviewed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
